name: dynamic_app
description: A server-driven dynamic Flutter app example
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.10.0
  carousel_slider: ^5.1.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
