name: dynamic_app
description: A server-driven dynamic Flutter app example
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.14.4
  carousel_slider: ^5.1.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  image_picker: ^1.0.4
  video_player: ^2.8.1
  webview_flutter: ^4.4.2
  #qr_code_scanner: ^1.0.2
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  fl_chart: ^1.1.1
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  share_plus: ^12.0.1
  syncfusion_flutter_pdfviewer: ^32.1.23
  file_picker: ^10.3.8
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_html: ^3.0.0-beta.2
  # QR scanner only for mobile - causes web compilation errors
  # qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
